name: barrel_generator
description: Generate barrel files for Dart using build_runner.
repository: https://github.com/AngeloAvv/barrel
issue_tracker: https://github.com/AngeloAvv/barrel/issues
version: 1.0.3

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  analyzer: ^6.5.0
  build: ^2.4.1
  source_gen: ^1.5.0
  barrel_annotation: ^1.0.0
  glob: ^2.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
